#!/bin/bash

# Opens an Akka cluster dashboard web page on the specified node, nodes 1-9.

usage() {
    echo "Usage: $0 [node] - Opens an Akka cluster dashboard web page on the specified node, nodes 1-9." ; exit 1
}

openDashboardWebPage() {
  node=$1

  if hash open 2>/dev/null; then
    open http://127.0.0.1:955$node/
elif hash xdg-open 2>/dev/null; then
    xdg-open http://127.0.0.1:955$node/
  fi
}

[ $# -eq 0 ] && usage

node=$1

if [[ $node =~ ^[1-9]$ ]] ; then
  openDashboardWebPage $node
else
  echo "Cluster node number $node is invalid. The node number must be 1 through 9."
  usage
fi
