#!/bin/bash

# Use this script to unblock all blocked Akka cluster nodes network access.
# Root user (sudo) is required to create blocking rules.

usage() {
  echo "Usage: $0 nodes - Unblock all blocked cluster nodes." ; exit 1
}

unblock() {
  if hash pfctl 2>/dev/null; then
    pfctl -f /etc/pf.conf 2>/dev/null
  elif hash iptables 2>/dev/null; then
    iptables -F
  else
    echo "This command is currently only available on OSX or Linux systems."
  fi
}

if ! [ $(id -u) = 0 ]; then
  echo "Root user (sudo) required."
  exit 1
fi

unblock
